Added preliminary support for zap, currently fails:
================================================================================
           Error executing action `delete` on resource 'zap_directory[/etc/nginx/conf.d]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `path' for LWRP resource nginx_server_block from cookbook nginx_server

           Cookbook Trace:
           ---------------
       /tmp/kitchen/cache/cookbooks/zap/libraries/directory.rb:52:in `select'
           /tmp/kitchen/cache/cookbooks/zap/libraries/default.rb:123:in `call'
           /tmp/kitchen/cache/cookbooks/zap/libraries/default.rb:123:in `block in iterate'
           /tmp/kitchen/cache/cookbooks/zap/libraries/default.rb:122:in `iterate'
           /tmp/kitchen/cache/cookbooks/zap/libraries/default.rb:99:in `action_delete'

           ---------------------
           # In /tmp/kitchen/cache/cookbooks/nginx_server/recipes/default.rb

            24:   zap_directory '/etc/nginx/conf.d' do
            25:     klass [Chef::Resource::File, Chef::Resource::Template,
        26:            Chef::Resource::NginxServerBlock]
            27:   end
            28: end

       ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/nginx_server/recipes/default.rb:24:in `from_file'

           zap_directory("/etc/nginx/conf.d") do
             provider Chef::Provider::ZapDirectory
             action :delete
             retries 0

             default_guard_interpreter :default
             delayed true
             pattern "*"
             klass [Chef::Resource::File, Chef::Resource::Template, LWRP resource nginx_server_block from cookbook nginx_server]
             declared_type :zap_directory
         cookbook_name "nginx_server"
             recipe_name "default"
           end

       Running handlers:
       [2015-11-16T23:10:43+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-11-16T23:10:43+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 09 seconds
       [2015-11-16T23:10:43+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-11-16T23:10:43+00:00] ERROR: zap_directory[/etc/nginx/conf.d] (nginx_server::default line 24) had an error: NoMethodError: undefined method `path' for LWRP resource nginx_server_block from cookbook nginx_server
       [2015-11-16T23:10:43+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)